spring:
    pcap:
        unsafe: false
        live:
            snapshotLength: 1500
            promiscuous: true
            rfmon: false
            timeout: 1000
            immediate: true
            timestampType: HOST
            timestampPrecision: MICRO
        offline:
            timestampPrecision: MICRO
