name: Build

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  hotspot-deployment:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setting up deployment
        run: |
          echo "${{ secrets.mvn_settings_base64 }}" | base64 --decode > .mvn/release-settings.xml
          gpg --keyserver keyserver.ubuntu.com --recv 3941ec75119f398a
          echo "${{ secrets.gpg_secring_base64 }}" | base64 --decode > ~/.gnupg/secring.gpg
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Build modules
        run: |
          [ -d /tmp/jdk-14 ] && echo 'JDK-14 is already installed' || ./.github/scripts/install-jdk.sh -w /tmp -u https://download.java.net/java/early_access/panama/1/openjdk-14-panama+1-15_linux-x64_bin.tar.gz --os linux-x64
          mkdir -p ~/.m2 && cp .mvn/toolchains.xml ~/.m2
          export JAVA_HOME_8=${JAVA_HOME}
          export JAVA_HOME_14=/tmp/jdk-14
          export JAVA_HOME=${JAVA_HOME_14}
          echo "JAVA_HOME_8 = $JAVA_HOME_8"
          echo "JAVA_HOME_14 = $JAVA_HOME_14"
          echo "JAVA_HOME = $JAVA_HOME"
          ./mvnw -B -s .mvn/release-settings.xml package -Plegacy-support -DskipTests
