name: Deploy Documentations

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    name: Deploy Documentations
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        java: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - uses: actions/checkout@v2
        with:
          fetch-depth: 1


      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64


      - name: Generate docs
        run: |
          export JAVA_HOME_8=${JAVA_HOME}
          ./mvnw -B -pl 'docs' clean package -Pdocs


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./docs/target/generated-docs
