name: Release

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deployment:
    name: Deployment
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - uses: actions/checkout@v2
        with:
          fetch-depth: 1


      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: actions/setup-panama
        run: |
          sudo mkdir -p /usr/local/jvm
          sudo chown -R $(whoami) /usr/local/jvm
          ./.github/scripts/install-jdk.sh -f panama -w /tmp -t /usr/local/jvm/panama -v


      - name: Setting up deployment
        run: |
          echo "${{ secrets.mvn_settings_base64 }}" | base64 --decode > .mvn/release-settings.xml
          gpg --keyserver keyserver.ubuntu.com --recv 3941ec75119f398a
          echo "${{ secrets.gpg_secring_base64 }}" | base64 --decode > ~/.gnupg/secring.gpg


      - name: Deploy modules
        run: |
          export JAVA_HOME_8=${JAVA_HOME}
          export JAVA_HOME=/usr/local/jvm/panama
          echo "JAVA_HOME_8 = $JAVA_HOME_8"
          echo "JAVA_HOME = $JAVA_HOME"
          ./mvnw -B -t .mvn/toolchains.xml -s .mvn/release-settings.xml deploy -Prelease -Plegacy-support -DskipTests
